server:
  port: 9800

spring:
  application:
    name: cas-generator

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cas_dap_access?useSSL=false&serverTimezone=UTC
    username: root
    password: root123456
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10