spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cas_dap_access?useSSL=false&serverTimezone=UTC
    username: cas-dap-access
    password: 53dzWZfZJ5bH7WWE
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 10