server:
  port: 9000
  servlet:
    context-path: /dap-admin

spring:
  application:
    name: cas-dap-admin
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
