spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cas_dap_access?useSSL=false&serverTimezone=UTC
    username: cas_dap_access
    password: 73AiGQ7bQWDtf4MB
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 10