spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.120:3306/cas_dap?useSSL=false&serverTimezone=UTC
    username: root
    password: root123456
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 10
